// <auto-generated />
using System;
using FaziCricketClub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FaziCricketClub.Infrastructure.Migrations
{
    [DbContext(typeof(CricketClubDbContext))]
    [Migration("20251226150550_AddJoinedOnToMember")]
    partial class AddJoinedOnToMember
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FaziCricketClub.Domain.Entities.BattingScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Balls")
                        .HasColumnType("int");

                    b.Property<int>("BattingOrder")
                        .HasColumnType("int");

                    b.Property<int?>("DismissalBowlerMemberId")
                        .HasColumnType("int");

                    b.Property<int?>("DismissalFielderMemberId")
                        .HasColumnType("int");

                    b.Property<string>("DismissalType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FixtureId")
                        .HasColumnType("int");

                    b.Property<int>("Fours")
                        .HasColumnType("int");

                    b.Property<bool>("IsOut")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Runs")
                        .HasColumnType("int");

                    b.Property<int>("Sixes")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.HasIndex("MemberId");

                    b.ToTable("BattingScores", (string)null);
                });

            modelBuilder.Entity("FaziCricketClub.Domain.Entities.BowlingFigure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FixtureId")
                        .HasColumnType("int");

                    b.Property<int>("Maidens")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("NoBalls")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Overs")
                        .HasColumnType("decimal(4,1)");

                    b.Property<int>("RunsConceded")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("Wickets")
                        .HasColumnType("int");

                    b.Property<int>("Wides")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.HasIndex("MemberId");

                    b.ToTable("BowlingFigures", (string)null);
                });

            modelBuilder.Entity("FaziCricketClub.Domain.Entities.Fixture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<string>("CompetitionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Fixtures");
                });

            modelBuilder.Entity("FaziCricketClub.Domain.Entities.FixtureAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FixtureId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.HasIndex("MemberId");

                    b.ToTable("FixtureAvailabilities", (string)null);
                });

            modelBuilder.Entity("FaziCricketClub.Domain.Entities.FixtureSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CaptainMemberId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FixtureId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("WicketKeeperMemberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId")
                        .IsUnique();

                    b.ToTable("FixtureSelections", (string)null);
                });

            modelBuilder.Entity("FaziCricketClub.Domain.Entities.FixtureSelectionPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BattingOrder")
                        .HasColumnType("int");

                    b.Property<int>("FixtureSelectionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPlaying")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FixtureSelectionId");

                    b.HasIndex("MemberId");

                    b.ToTable("FixtureSelectionPlayers", (string)null);
                });

            modelBuilder.Entity("FaziCricketClub.Domain.Entities.MatchResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AwayTeamOvers")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AwayTeamRuns")
                        .HasColumnType("int");

                    b.Property<int?>("AwayTeamWickets")
                        .HasColumnType("int");

                    b.Property<int>("FixtureId")
                        .HasColumnType("int");

                    b.Property<decimal?>("HomeTeamOvers")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("HomeTeamRuns")
                        .HasColumnType("int");

                    b.Property<int?>("HomeTeamWickets")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("PlayerOfTheMatchMemberId")
                        .HasColumnType("int");

                    b.Property<string>("ResultSummary")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("WinningTeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId")
                        .IsUnique();

                    b.ToTable("MatchResults", (string)null);
                });

            modelBuilder.Entity("FaziCricketClub.Domain.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("JoinedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("FaziCricketClub.Domain.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("FaziCricketClub.Domain.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("MemberTeam", b =>
                {
                    b.Property<int>("MembersId")
                        .HasColumnType("int");

                    b.Property<int>("TeamsId")
                        .HasColumnType("int");

                    b.HasKey("MembersId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("MemberTeam");
                });

            modelBuilder.Entity("FaziCricketClub.Domain.Entities.BattingScore", b =>
                {
                    b.HasOne("FaziCricketClub.Domain.Entities.Fixture", "Fixture")
                        .WithMany("BattingScores")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FaziCricketClub.Domain.Entities.Member", "Member")
                        .WithMany("BattingScores")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fixture");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("FaziCricketClub.Domain.Entities.BowlingFigure", b =>
                {
                    b.HasOne("FaziCricketClub.Domain.Entities.Fixture", "Fixture")
                        .WithMany("BowlingFigures")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FaziCricketClub.Domain.Entities.Member", "Member")
                        .WithMany("BowlingFigures")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fixture");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("FaziCricketClub.Domain.Entities.Fixture", b =>
                {
                    b.HasOne("FaziCricketClub.Domain.Entities.Team", "AwayTeam")
                        .WithMany("AwayFixtures")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FaziCricketClub.Domain.Entities.Team", "HomeTeam")
                        .WithMany("HomeFixtures")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FaziCricketClub.Domain.Entities.Season", "Season")
                        .WithMany("Fixtures")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("FaziCricketClub.Domain.Entities.FixtureAvailability", b =>
                {
                    b.HasOne("FaziCricketClub.Domain.Entities.Fixture", "Fixture")
                        .WithMany("Availabilities")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FaziCricketClub.Domain.Entities.Member", "Member")
                        .WithMany("FixtureAvailabilities")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fixture");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("FaziCricketClub.Domain.Entities.FixtureSelection", b =>
                {
                    b.HasOne("FaziCricketClub.Domain.Entities.Fixture", "Fixture")
                        .WithOne("Selection")
                        .HasForeignKey("FaziCricketClub.Domain.Entities.FixtureSelection", "FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fixture");
                });

            modelBuilder.Entity("FaziCricketClub.Domain.Entities.FixtureSelectionPlayer", b =>
                {
                    b.HasOne("FaziCricketClub.Domain.Entities.FixtureSelection", "FixtureSelection")
                        .WithMany("Players")
                        .HasForeignKey("FixtureSelectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FaziCricketClub.Domain.Entities.Member", "Member")
                        .WithMany("FixtureSelections")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FixtureSelection");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("FaziCricketClub.Domain.Entities.MatchResult", b =>
                {
                    b.HasOne("FaziCricketClub.Domain.Entities.Fixture", "Fixture")
                        .WithOne("MatchResult")
                        .HasForeignKey("FaziCricketClub.Domain.Entities.MatchResult", "FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fixture");
                });

            modelBuilder.Entity("MemberTeam", b =>
                {
                    b.HasOne("FaziCricketClub.Domain.Entities.Member", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FaziCricketClub.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FaziCricketClub.Domain.Entities.Fixture", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("BattingScores");

                    b.Navigation("BowlingFigures");

                    b.Navigation("MatchResult");

                    b.Navigation("Selection");
                });

            modelBuilder.Entity("FaziCricketClub.Domain.Entities.FixtureSelection", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("FaziCricketClub.Domain.Entities.Member", b =>
                {
                    b.Navigation("BattingScores");

                    b.Navigation("BowlingFigures");

                    b.Navigation("FixtureAvailabilities");

                    b.Navigation("FixtureSelections");
                });

            modelBuilder.Entity("FaziCricketClub.Domain.Entities.Season", b =>
                {
                    b.Navigation("Fixtures");
                });

            modelBuilder.Entity("FaziCricketClub.Domain.Entities.Team", b =>
                {
                    b.Navigation("AwayFixtures");

                    b.Navigation("HomeFixtures");
                });
#pragma warning restore 612, 618
        }
    }
}
